name: CapyPass
version: '1.0-SNAPSHOT'
main: me.GreatScott42.capyPass.CapyPass
api-version: '1.21'
commands:
  battlepass:
    description: battlepass information
    usage: /battlepass
    permission: Capypass.battlepass
  capypass:
    description: Capypass admin commands
    usage: /capypass <player> <premium-free> /capypass <player> <level>
    permission: Capypass.capypass
  misions:
    description: misions information
    usage: /misions
    permission: CapyPass.misions
